language: go
sudo: false
go:
    - 1.x
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - go test -cover ./... -coverprofile=coverage.txt -covermode=atomic
notifications:
    email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
