language: go
sudo: false
go:
    - 1.*
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - go test -cover ./...
notifications:
    email: false
